### ISSUE TITLE
The gateway  of the container is unreachable.

### ISSUE THREAD

**Issue by IkuEisou** [cloudfoundry/warden#107] opened 2016-02-01 11:39 UTC
I want to make a warden container access to the internet behind a proxy,but it failed that said  no route to the proxy. 
I'm sure that the CF environment  variables http_proxy has been setup, and the proxy works well on the host of CF.

I tried to login the container and set the proxy, but I found that the gateway is unreachable with ping.
> Kernel IP routing table
> Destination     Gateway         Genmask         Flags   MSS Window  irtt Iface
> 0.0.0.0         10.254.0.45     0.0.0.0         UG        0 0          0 w-19am5gmphtf-1
> 10.254.0.44     0.0.0.0         255.255.255.252 U         0 0          0 w-19am5gmphtf-1

The information of the warden server virtual network-card is as below.  
> w-19am5gmphtf-0 Link encap:Ethernet  HWaddr aa:a3:83:a8:5d:16
>           UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
>           RX packets:134 errors:0 dropped:0 overruns:0 frame:0
>           TX packets:1413 errors:0 dropped:0 overruns:0 carrier:0
>           collisions:0 txqueuelen:1000
>           RX bytes:7503 (7.5 KB)  TX bytes:345451 (345.4 KB)
> 

It should be assigned a IP (10.254.0.45), but it didn't get it.
The IP address of the  warden server virtual network-card is dynamically assigned by CF, so I don't think it's  necessary to setup a static IP address for it on the host.
Could you tell me how to fix it?

**Comment by ScarletTanager** [comment] 2016-02-04 18:39
Hello,

We're not really sure what is causing your problem. When you say that you, "tried to login the container," what _specifically_ did you do?  We're trying to figure out if you are actually in one of the running warden containers or in the runner vm.

It would be helpful as well to know more about your deployment - is this a full-blown/production deployment, or is it a bosh-lite deployment?  And what do you mean by "behind a proxy" - where did you "set the proxy?"

For comparison's sake, here is the routing table from the runner vm in a bosh-lite deployment:

    bosh_ndgrkjqvj@7c912136-10ee-4487-ab14-d8b366399b2b:~$ netstat -rn
    Kernel IP routing table
    Destination     Gateway         Genmask         Flags   MSS Window  irtt Iface
    0.0.0.0         10.244.0.25     0.0.0.0         UG        0 0          0 wbpj43b3r48c-1
    10.244.0.24     0.0.0.0         255.255.255.252 U         0 0          0 wbpj43b3r48c-1
    10.254.0.4      0.0.0.0         255.255.255.252 U         0 0          0 w-19auf719t2f-0`

Note that the default route is over the interface of the runner VM itself, not the warden interface.

If you could provide us more information, we can try and get you some answers.

Thanks,
@ScarletTanager and @jberkhahn 
CF runtime_og team

**Comment by IkuEisou** [comment] 2016-02-05 06:08
Hello, Sandy. Thank you  for your help.
I deployed the CF on a PC with [cf_nise_installer](https://github.com/yudai/cf_nise_installer)

And I deployed a app with `cf push` and got a warden container for the app.
I login the warden container with 'wsh' like this.
`/var/vcap/packages/warden/warden/src/wsh/wsh --socket /var/vcap/data/warden/depot/WARDEN-HANDLE/run/wshd.sock --user vcap `

The  "behind a proxy"  means the host(PC with deploying CF ) is in a 10.x.x.x network and it's necessary to set a proxy(also in a 10.x.x.x network ) to access to the internet.

Well, let me show the route and the IP of the  warden container.
```
vcap@19am5gmphtf:~$ netstat -nr
Kernel IP routing table
Destination     Gateway         Genmask         Flags   MSS Window  irtt Iface
0.0.0.0         10.254.0.45     0.0.0.0         UG        0 0          0 w-19am5gmphtf-1
10.254.0.44     0.0.0.0         255.255.255.252 U         0 0          0 w-19am5gmphtf-1

vcap@19am5gmphtf:~$ cat /etc/hosts
127.0.0.1 localhost
10.254.0.46 19am5gmphtf

```

I think 10.254.0.45   is the IP of  the  w-19am5gmphtf-0, but w-19am5gmphtf-0 hasn't got the IP from the host.

**Comment by sykesm** [comment] 2016-02-05 13:19
@IkuEisou, warden assigns IP addresses to both sides of the veth pair from a /30 subnet it reserves from its [pool]. (The address pool to use is configurable.) The IP allocations are passed from the warden server to the script via environment variables. This data should live in `etc/config` within the container directory of the container depot.

The host side interface of the veth pair will always be named with a `-0` suffix and the container side interface will be named with a `-1` suffix. The host veth interface's IP address will be one less than the container's and the host veth interface will be configured as the default gateway for the container. From that point on, the configuration of the host networking stack (iptables, routes, and network forwarding).

What you show in your output for the container looks appropriate for a 10.254.0.44/30 subnet where the container gets 10.254.0.45 and the container gets 10.254.0.46 and the default route goes via the host.

You should carefully evaluate the iptables filters that are active on your host system and verify that nothing is preventing packets from flowing out of the container network to the destination you are trying to reach. In particular, warden security groups deny network access by default so allowed networks must be configured for warden job (allow_networks) or `net_out` operations must be performed against a warden container (the is how DEA security groups are implemented).

Given the nise installer is not a deployment mechanism that we support, I don't know that we will be able to help you resolve this problem. You may have better luck working with others that have deployed that way but the problem is that unlike bosh, the nise installer does not start Cloud Foundry jobs in a well known environment.

If you deploy with bosh and continue to have issues, we may be able to help you more. I would strongly recommend you look at using bosh-lite for your single host deployments.

[pool]: https://github.com/cloudfoundry/warden/blob/master/warden/root/linux/skeleton/lib/hook-parent-after-clone.sh#L62

**Comment by IkuEisou** [comment] 2016-02-06 15:34
@sykesm Thank you for your help.
I'm sure the  container side interface is  w-19am5gmphtf-1(IP is 10.254.0.46.), and the gateway of default route  is 10.254.0.45 in the container.
I think the 10.254.0.45 should be the IP of the host side interface w-19am5gmphtf-0, but the  10.254.0.45 hasn't been assigned to  w-19am5gmphtf-0 on the host.

Because the host side interface w-19am5gmphtf-0 hasn't got a IP from the host, however setup the security groups, it doesn't work.

So I want to know why the host side interface w-19am5gmphtf-0 hasn't got a IP from the host, and it should not cause by the setup of the security groups  or iptables.

**Comment by sykesm** [comment] 2016-02-06 15:49
@IkuEisou, I pointed you to the line of code that creates the host side adapter and sets the address; it was linked in my previous comment but I'll put it here for clarity:
> https://github.com/cloudfoundry/warden/blob/master/warden/root/linux/skeleton/lib/hook-parent-after-clone.sh#L62

Since that script is run with `set -o errexit`, the container creation would have failed if assigning the address to the host-side interface failed.

With that, I would like to point out again that nise-bosh is not an install mechanism we support as it provides no guarantees about the environment hosting the bosh jobs. In particular, the network management daemons and utilities in your operating system may be altering the state of the host-side adapter after warden brings it up.

If you have this problem in a bosh or bosh-lite managed install, we are better positioned to help. Short of that, I think you're going to have to identify where the IP gets lost between the time warden sets it up and you look at it.

**Comment by sykesm** [comment] 2016-02-10 13:41
@IkuEisou I'm going to close this issue for now. As I said earlier, if you run into this problem within the context of a bosh deployment, we're much more likely to be able to help.

My last suggestion would be for you to look closely at the network manager component of your chosen operating system. Many Linux distributions will attempt to take control of new network interfaces that show up on the machine and that may very well be what's happening here.

**Closed by sykesm** 2016-02-10 13:41 UTC

**Comment by IkuEisou** [comment] 2016-02-19 06:12
@sykesm  Thank you very much for your help.
I found the host side interface got a IP when the container just stated with `cf start` or  `cf restart` at first, but the host side interface lost this IP  after a few minutes.

I tried to give it the same IP again with `ifconfig` , and it worked  a few minutes.
Then it lost the IP again. 

There is no description about what happened in the log of warden and `dmesg`.
The config file of the container as following. 
```
# cat /var/vcap/data/warden/depot/19c2oe1rvaj/etc/config
id=19c2oe1rvaj
network_netmask=255.255.255.252
network_host_ip=10.254.0.13
network_host_iface=w-19c2oe1rvaj-0
network_container_ip=10.254.0.14
network_container_iface=w-19c2oe1rvaj-1
user_uid=20003
rootfs_path=/var/vcap/data/packages/rootfs_cflinuxfs2/c3a0b489fe1669c605c6804765f52e278bfdc842/rootfs
allow_nested_warden=false

```
My linux distributions is ubuntu14, and is there something will carry off the ip from the  host side interface?
